In [1]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
df = pd.read_json("kinopoisk.jsonl", lines=True)
df.head()

part   movie_name  review_id         author       date  \
0  top250  Блеф (1976)      17144      Come Back 2011-09-24   
1  top250  Блеф (1976)      17139        Stasiki 2008-03-04   
2  top250  Блеф (1976)      17137       Flashman 2007-03-04   
3  top250  Блеф (1976)      17135  Sergio Tishin 2009-08-17   
4  top250  Блеф (1976)      17151        Фюльгья 2009-08-20   

                                               title   grade3  grade10  \
0                             Плакали наши денежки ©     Good     10.0   
1                                               None     Good      0.0   
2                                               None     Good     10.0   
3  " Черное, красное, ерунда это все. Выигрывает ...     Good      0.0   
4                «Он хотел убежать? Да! Блеф, блеф…»  Neutral      7.0   

                                             content  
0  \n"Блеф» — одна из моих самых любимых комедий....  
1  \nАдриано Челентано продолжает радовать нас св...  
2  \nНесомненно, это один из великих фильмов 80-х...  
3  \nЭта фраза на мой взгляд отражает сюжет несом...  
4  \n- как пела Земфира, скорее всего, по соверше...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36591 entries, 0 to 36590
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   part        36591 non-null  object        
 1   movie_name  36591 non-null  object        
 2   review_id   36591 non-null  int64         
 3   author      35802 non-null  object        
 4   date        36591 non-null  datetime64[ns]
 5   title       27472 non-null  object        
 6   grade3      36591 non-null  object        
 7   grade10     36591 non-null  float64       
 8   content     36591 non-null  object        
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 2.5+ MB


In [4]:
df.describe()

review_id                           date       grade10
count  36591.000000                          36591  3.659100e+04
mean   16983.233910  2010-02-05 14:25:33.032712960  2.817212e+02
min        0.000000            2004-07-04 00:00:00  0.000000e+00
25%     9147.500000            2009-04-27 00:00:00  0.000000e+00
50%    18295.000000            2010-04-18 00:00:00  8.000000e+00
75%    25338.500000            2011-02-14 00:00:00  1.000000e+01
max    30694.000000            2012-11-26 00:00:00  1.000000e+07
std     8934.050949                            NaN  5.227986e+04

In [5]:
# Получение уникальных значений в колонке "part"
unique_parts = df["movie_name"].unique()

# Вывод уникальных значений
print(f"Уникальные значения в колонке 'part': {unique_parts}")

Уникальные значения в колонке 'part': ['Блеф (1976)' 'Малыш (1921)'
 'Шерлок Холмс и доктор Ватсон Охота на тигра (1980)'
 'Рапунцель Запутанная история (2010)' 'Как приручить дракона (2010)'
 'Корпорация монстров (2001)' 'Шестое чувство (1999)'
 'Пока не сыграл в ящик (2007)' 'ВАЛЛ·И (2008)' 'Апокалипсис (2006)'
 'Назад в будущее (1985)' 'Самый быстрый «Индиан» (2005)'
 'Достучаться до небес (1997)' 'Казино (1995)' 'В диких условиях (2007)'
 'Отец солдата (1964)' 'Непрощенный (1992)' 'Золотая лихорадка (1925)'
 'Храброе сердце (1995)' 'Одиннадцать друзей Оушена (2001)'
 'Один дома (1990)' 'Красавица и чудовище (1991)'
 'Шерлок Холмс Игра теней (2011)' 'Проверка на дорогах (1971)'
 'Судьба человека (1959)' 'Жизнь в розовом цвете (2007)' 'Мотылек (1973)'
 'Подмена (2008)' 'Лис и пес (1981)' 'Шерлок Холмс (2009)'
 'Семь самураев (1954)' 'Гран Торино (2008)' 'Сонная Лощина (1999)'
 'Шерлок Холмс и доктор Ватсон Собака Баскервилей (1981)'
 'Запах женщины (1992)' 'Курьер (1986)' 'Игры разум

In [6]:
# Количество отзывов на каждый фильм и количество фильмов.
counts = df.groupby("movie_name").size()
counts

movie_name
1+1 (2011)                                                   34
12 разгневанных мужчин (1957)                                78
12 стульев (1971)                                            14
18-летняя девственница (2009)                                12
2012 Судный день (2008)                                      12
                                                           ... 
Эта замечательная жизнь (1946)                               45
Эффект бабочки (2004)                                       206
Я - Сэм (2001)                                              112
Я всегда буду знать, что вы сделали прошлым летом (2006)     18
Яйцеголовые (1993)                                            4
Length: 350, dtype: int64

In [7]:
# Количество оценок по колонке grade3
count_grade3 = df.groupby("grade3").size()
count_grade3

grade3
Bad         4751
Good       27264
Neutral     4576
dtype: int64

In [8]:
# Количество оценок по колонке grade10
count_grade3_unique = df["grade3"].unique()
count_grade3_unique

array(['Good', 'Neutral', 'Bad'], dtype=object)

In [9]:
# Количество оценок по колонке grade10
count_grade10 = df["grade10"].unique()
count_grade10

array([1.000e+01, 0.000e+00, 7.000e+00, 9.000e+00, 8.000e+00, 5.000e+00,
       1.000e+00, 6.000e+00, 2.000e+00, 4.000e+00, 8.500e+00, 9.500e+00,
       4.500e+00, 1.200e+01, 1.000e+02, 7.500e+00, 1.050e+01, 3.000e+00,
       1.100e+01, 6.500e+00, 2.000e+01, 9.990e+00, 9.900e+00, 9.700e+00,
       7.900e+00, 8.900e+00, 8.200e+00, 3.500e+00, 6.300e+00, 1.000e+03,
       7.100e+00, 7.200e+00, 1.100e+02, 2.500e+00, 9.100e+00, 1.000e+07,
       6.800e+00, 8.300e+00, 6.200e+00, 1.500e+01, 8.600e+00, 7.300e+00,
       5.500e+00, 7.700e+00, 9.800e+00, 9.400e+00, 1.400e+01, 9.796e+00,
       7.400e+00, 7.890e+00, 6.600e+00, 8.700e+00, 7.800e+00, 5.800e+00,
       7.999e+00, 6.700e+00, 1.005e+05, 5.000e-01, 1.010e+01, 1.500e+00,
       4.600e+00, 1.000e-01, 3.400e+00, 1.800e+00, 1.000e-02, 2.700e+00,
       1.000e-09, 1.000e-05, 1.000e-06])

In [10]:
data = df[['grade3', 'content']]
data.head()

grade3                                            content
0     Good  \n"Блеф» — одна из моих самых любимых комедий....
1     Good  \nАдриано Челентано продолжает радовать нас св...
2     Good  \nНесомненно, это один из великих фильмов 80-х...
3     Good  \nЭта фраза на мой взгляд отражает сюжет несом...
4  Neutral  \n- как пела Земфира, скорее всего, по соверше...

In [38]:
label_encoder = LabelEncoder()
label_encoder.fit(data['grade3'].unique()) 
data.loc[:, 'labels'] = label_encoder.transform(data['grade3']) 
# Выводим первые строки DataFrame
data = data[['labels', 'content']]
data.head(10)

labels                                            content
0       1  \n"Блеф» — одна из моих самых любимых комедий....
1       1  \nАдриано Челентано продолжает радовать нас св...
2       1  \nНесомненно, это один из великих фильмов 80-х...
3       1  \nЭта фраза на мой взгляд отражает сюжет несом...
4       2  \n- как пела Земфира, скорее всего, по соверше...
5       1  \nБесспорный классический шедевр, который и че...
6       1  \n- Ну, так что ты скажешь по поводу нашей сов...
7       2  \nФинансовая акула Белль Дюк имеет давние счёт...
8       1  \nВесьма забавное и легкое кино. Челентано как...
9       1  \nНаверное, всё-таки самый лучший фильм с учас...

In [39]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [40]:
import json

import numpy as np
import pandas as pd
from typing import Tuple
import matplotlib.pyplot as plt

#### Word2Vec
import gensim
from gensim.models import Word2Vec

####
import torch
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F
import torch.nn as nn
import torchutils as tu
from sklearn.model_selection import train_test_split
from collections import Counter

from torchmetrics.classification import BinaryAccuracy
from src.rnn_preprocessing import (
                                data_preprocessing, 
                                preprocess_single_string, 
                                padding, 
                                get_words_by_freq
                                )
from src.train_rnn import train_attention_lstm

In [41]:
# Преобразование списка словарей в DataFrame
reviews = data['content'].tolist()
preprocessed = [data_preprocessing(review) for review in reviews]

In [42]:
preprocessed[10]

'«блеф» — комедия серджио корбуччи года один из любимых фильмов зрителей в советский период в данной ленте идет речь о мошеннике феликсе феличе — что означает счастье и о его многочисленных аферах както раз феликс сбегает из тюрьмы не дав сделать то же самое другому заключенному после чего ему помогают два незнакомых ему человека что удивляет самого героя но как оказывается впоследствии его приняли не за того теперь он должен освободить филиппа бэнга но на этом приключения не заканчивается освобождённый заключенный предлагает сотрудничество после нескольких проверок филипп а именно им оказался заключенный хочет провернуть дело чтобы отомстить своей давней знакомой бель дюк параллельно блефу главных героев развивается любовная линия феликса и дочери филиппа — шарлотты фильм очень легкий веселый с интересными поворотами сюжета что является явным плюсом андриано челентано бесподобен как всегда очень интересно смотреть на его героя наблюдать за его выходками образу бойкого феликса противоп

In [15]:
# Анализируем частоты слов и выбираем только те, которые встречаются чаще порога
corpus = [word for text in preprocessed for word in text.split()]
sorted_words = Counter(corpus).most_common()
sorted_words = get_words_by_freq(sorted_words, 200)
sorted_words[-10:]

[('небес', 201),
 ('третью', 201),
 ('попытку', 201),
 ('грязи', 201),
 ('актрис', 201),
 ('пошёл', 201),
 ('роботов', 201),
 ('хичкок', 201),
 ('бертона', 201),
 ('ким', 201)]

In [16]:


# Создаем словарь слово: индекс
vocab_to_int = {w:i+1 for i, (w,c) in enumerate(sorted_words)}
# vocab_to_int

In [17]:
import json 
with open('vocab2int.json', 'w') as f:
    json.dump(vocab_to_int, f)

In [18]:
list(vocab_to_int.items())[:10]

[('и', 1),
 ('в', 2),
 ('не', 3),
 ('что', 4),
 ('на', 5),
 ('—', 6),
 ('с', 7),
 ('это', 8),
 ('но', 9),
 ('фильм', 10)]

In [19]:
# Конвертируем слова в индексы
reviews_int = []
for text in preprocessed:
    r = [vocab_to_int[word] for word in text.split() if vocab_to_int.get(word)]
    reviews_int.append(r)
print([i for i in reviews_int[0]])
print(preprocessed[0])

[6, 243, 14, 618, 217, 635, 2383, 33, 10, 11, 925, 391, 62, 1393, 55, 11, 78, 11, 368, 16, 401, 84, 3, 171, 3, 1955, 594, 2392, 2809, 49, 26, 1590, 7, 28, 167, 12, 11, 421, 8, 759, 102, 2, 51, 843, 878, 1462, 766, 4, 5, 16, 2, 16, 1110, 259, 79, 88, 11, 214, 4, 1, 1, 2071, 21, 268, 4, 31, 127, 45, 576, 50, 539, 68, 34, 5, 81, 60, 111, 57, 78, 148, 807, 7, 671, 15, 128, 1, 91, 4, 688, 18, 705, 13, 193, 205, 432, 154, 2481, 60, 161, 202, 14, 4808, 4423, 79, 3, 391, 1096, 7, 293, 371, 243, 1651, 125, 5, 260, 14, 191, 130, 15, 20, 92, 20, 92, 13, 102, 29, 94, 67, 2, 231, 14, 587, 15, 7, 2, 1, 15, 239, 87, 804, 14, 49, 40, 821, 124, 69, 4, 15, 170, 2, 57, 378, 57, 125, 21, 1753, 154, 54, 88, 1, 193, 145, 10, 865, 194, 43, 1170, 3356, 334, 569, 148, 2342, 31, 167, 7, 305, 9, 808, 94, 5, 2248, 636, 246, 22, 1018, 1, 67, 3, 76, 15, 44, 145, 1180, 63, 69, 12, 40, 3479, 2353, 587, 2317, 206, 2, 50, 179, 30, 55, 208, 2165, 67, 143, 899, 2, 94, 937, 1049, 80, 49, 40, 128, 1, 2, 377, 330, 50, 3682,

In [20]:
w2v_input = []
for review in preprocessed:
    cur_review = []
    for word in review.split():
        if vocab_to_int.get(word):
            cur_review.append(word)
    w2v_input.append(cur_review)
print(f'Total reviews: {len(w2v_input)}')
print(f'Random review for word2vec: {w2v_input[np.random.randint(0, 50000)]}')

Total reviews: 36591
Random review for word2vec: ['действительно', 'порой', 'мы', 'на', 'но', 'даже', 'пойти', 'и', 'получить', 'свой', 'судьба', 'даёт', 'шанс', 'но', 'какой', 'будет', 'сделан', 'выбор', 'решать', 'вам', 'как', 'хорошо', 'когда', 'появляется', 'который', 'вас', 'даст', 'и', 'навсегда', 'останется', 'в', 'но', 'как', 'сложно', 'добиться', 'человека', 'который', 'никого', 'не', 'в', 'свои', 'эмоции', 'и', 'переживания', 'подобрать', 'слова', 'узнать', 'что', 'у', 'уилла', 'в', 'душе', 'и', 'почему', 'он', 'такой', 'образ', 'жизни', 'вот', 'задача', 'диалоги', 'и', 'темы', 'которые', 'не', 'вас', 'и', 'эмоции', 'жизни', 'и', 'гениальность', 'понять', 'себя', 'сделать', 'шаг', 'судьбе', 'и', 'свою', 'чтобы', 'выйти', 'в', 'море', 'многое', 'нужно', 'преодолеть', 'из']


In [21]:
VOCAB_SIZE = len(vocab_to_int) + 1  # размер словаря вместе с токеном padding
EMBEDDING_DIM = 64 # embedding_dim 

In [22]:
# Обучим Word2Vec
wv = Word2Vec(
    vector_size=EMBEDDING_DIM # размерность вектора для слова
    )
# Сначала word2vec составляет словарь
wv.build_vocab(w2v_input)
print(f'Total reviews: {wv.corpus_count}')

Total reviews: 36591


In [23]:
# Далее обучаем
wv.train(
    corpus_iterable=w2v_input, 
    total_examples=wv.corpus_count, 
    epochs=10
    )

(64250162, 82346360)

In [29]:
# Создаем слой эмбеддинга
embedding_matrix = np.zeros((VOCAB_SIZE, EMBEDDING_DIM))

# Бежим по всем словам словаря: если слово есть в word2vec, 
# достаем его вектор; если слова нет, то распечатываем его и пропускаем
for word, i in vocab_to_int.items():
    try:
        embedding_vector = wv.wv[word]
        embedding_matrix[i] = embedding_vector
    except KeyError as e:
        pass
        print(f'{e}: word: {word}')
        
# Создаем предобученный эмбеддинг – этот слой в нашей сети обучаться не будет
embedding_layer = nn.Embedding.from_pretrained(torch.FloatTensor(embedding_matrix))
print(f'Number of words x EMEDDING_DIM: {embedding_matrix.shape}')

Number of words x EMEDDING_DIM: (5047, 64)


In [30]:
# Применяем padding
padded = padding(review_int=reviews_int, seq_len=64)
print(padded[5])

[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0 3635  250   39    1  262  159
   96   18   23   12    8   37    2  705]


In [43]:
data

labels                                            content
0           1  \n"Блеф» — одна из моих самых любимых комедий....
1           1  \nАдриано Челентано продолжает радовать нас св...
2           1  \nНесомненно, это один из великих фильмов 80-х...
3           1  \nЭта фраза на мой взгляд отражает сюжет несом...
4           2  \n- как пела Земфира, скорее всего, по соверше...
...       ...                                                ...
36586       0  \n      Ну с чего бы начать… Давненько я не пи...
36587       0  \n      Можно начать с того, что уже постер к ...
36588       1  \n      Фильм производства России, поэтому мно...
36589       0  \n      16 сентября на большие экраны вышел «м...
36590       0  \n      Эх, как я пыталась настроить себя поло...

[36591 rows x 2 columns]

In [45]:
# Train-Test Split
X_train, X_valid, y_train, y_valid = train_test_split(
    np.array(padded),
    data['labels'].values,
    test_size=0.2, random_state=1
)

In [46]:
y_train

array([1, 1, 1, ..., 1, 1, 2])

In [47]:
BATCH_SIZE = 64

train_data = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
valid_data = TensorDataset(torch.from_numpy(X_valid), torch.from_numpy(y_valid))
train_loader = DataLoader(train_data, shuffle=True, batch_size=BATCH_SIZE)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=BATCH_SIZE)

In [48]:
y_valid

array([1, 1, 0, ..., 2, 1, 1])

In [51]:
# посмотрим, что внутри
dataiter = iter(train_loader)
sample_x, sample_y = next(dataiter)

print('Sample input size: BATCH_SIZE x SEQ_LEN', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print('Sample input: \n', sample_y[:10])

Sample input size: BATCH_SIZE x SEQ_LEN torch.Size([64, 64])
Sample input: 
 tensor([[ 354,   23,   11,  ...,   45,  265,  168],
        [1416,   11,  371,  ...,  413, 2324,   38],
        [  25,   49,   26,  ...,  541, 4659,    2],
        ...,
        [  13,    4,   35,  ..., 1891, 1316,    5],
        [  24,    1,   22,  ...,   85,  154,  149],
        [   4, 4533,   98,  ...,  601,   79,    6]])
Sample input: 
 tensor([0, 1, 1, 1, 1, 1, 1, 1, 1, 0])


In [52]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [53]:
HIDDEN_SIZE = 32

In [54]:
class ConcatAttention(nn.Module):
    def __init__(
            self, 
            hidden_size: int = HIDDEN_SIZE
            ) -> None:
        
        super().__init__()
        self.hidden_size = hidden_size
        self.linear = nn.Linear(self.hidden_size, self.hidden_size)
        self.align  = nn.Linear(self.hidden_size * 2, self.hidden_size)
        self.tanh   = nn.Tanh()

    def forward(
            self, 
            lstm_outputs: torch.Tensor, # BATCH_SIZE x SEQ_LEN x HIDDEN_SIZE
            final_hidden: torch.Tensor  # BATCH_SIZE x HIDDEN_SIZE
            ) -> Tuple[torch.Tensor, torch.Tensor]:
        
        att_weights = self.linear(lstm_outputs)
        # print(f'After linear: {att_weights.shape, final_hidden.unsqueeze(2).shape}')
        att_weights = torch.bmm(att_weights, final_hidden.unsqueeze(2))
        # print(f'After bmm: {att_weights.shape}')
        att_weights = F.softmax(att_weights.squeeze(2), dim=1)
        # print(f'After softmax: {att_weights.shape}')
        cntxt       = torch.bmm(lstm_outputs.transpose(1, 2), att_weights.unsqueeze(2))
        # print(f'Context: {cntxt.shape}')
        concatted   = torch.cat((cntxt, final_hidden.unsqueeze(2)), dim=1)
        # print(f'Concatted: {concatted.shape}')
        att_hidden  = self.tanh(self.align(concatted.squeeze(-1)))
        # print(f'Att Hidden: {att_hidden.shape}')
        return att_hidden, att_weights

# Test on random numbers
ConcatAttention()(torch.randn(BATCH_SIZE, 128, HIDDEN_SIZE), torch.randn(BATCH_SIZE, HIDDEN_SIZE))[1].shape

torch.Size([64, 128])

In [55]:
attention = ConcatAttention(HIDDEN_SIZE)

In [56]:
tu.get_model_summary(attention, torch.randn(16, 32, HIDDEN_SIZE), torch.randn(16, HIDDEN_SIZE))

Layer       Kernel       Output      Params       FLOPs
0_linear   [32, 32]   [16, 32, 32]    1,056   1,032,192
1_align    [64, 32]       [16, 32]    2,080      65,024
2_tanh            -       [16, 32]        0       2,560
Total params: 3,136
Trainable params: 3,136
Non-trainable params: 0
Total FLOPs: 1,099,776 / 1.10 MFLOPs
-------------------------------------------------------
Input size (MB): 0.06
Forward/backward pass size (MB): 0.13
Params size (MB): 0.01
Estimated Total Size (MB): 0.21


In [68]:
SEQ_LEN = 32

In [69]:
class LSTMConcatAttention(nn.Module):
    def __init__(self) -> None:
        super().__init__()

        # self.embedding = nn.Embedding(VOCAB_SIZE, EMBEDDING_DIM)
        self.embedding = embedding_layer
        self.lstm = nn.LSTM(EMBEDDING_DIM, HIDDEN_SIZE, batch_first=True)
        self.attn = ConcatAttention(HIDDEN_SIZE)
        self.clf = nn.Sequential(
            nn.Linear(HIDDEN_SIZE, 128),
            nn.Dropout(),
            nn.Tanh(),
            nn.Linear(128, num_classes)
        )
    
    def forward(self, x):
        embeddings = self.embedding(x)
        outputs, (h_n, _) = self.lstm(embeddings)
        att_hidden, att_weights = self.attn(outputs, h_n.squeeze(0))
        out = self.clf(att_hidden)
        return out, att_weights

In [72]:
num_classes = 3 

In [75]:
model_concat = LSTMConcatAttention()
DEVICE='cuda'
criterion = nn.CrossEntropyLoss()
optimizer_concat = torch.optim.RMSprop(model_concat.parameters(), lr=0.001)
metric = nn.CrossEntropyLoss()

In [76]:
train_losses, val_losses, train_metric, val_metric, rnn_time = train_attention_lstm(
    10, model_concat, train_loader, valid_loader, optimizer_concat, criterion, metric
)

RuntimeError: expected scalar type Long but found Float